{
  "branches": [
    'main',
    { name: 'beta', prerelease: true },
    { name: 'alpha', prerelease: true }
  ],
  "repositoryUrl": "https://github.com/arkemishub/ui",
  "debug": "true",
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/changelog",
      {
        "changelogFile": "CHANGELOG.md"
      }
    ],
    '@semantic-release/npm',
    "@semantic-release/github",
    [
      "@semantic-release/git",
      {
        "assets": [ "CHANGELOG.md", "package.json" ],
        "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      }
    ],
  ]
}
