const sidebarConfig = [
  { title: "Getting Started" },
  { title: "Install", href: "/docs/install" },
  { title: "Theming", href: "/docs/theming" },
  { title: "Components" },
  { title: "Accordion", href: "/docs/components/accordion" },
  { title: "Alert", href: "/docs/components/alert" },
  { title: "Autocomplete", href: "/docs/components/autocomplete" },
  { title: "Avatar", href: "/docs/components/avatar" },
  { title: "Badge", href: "/docs/components/badge" },
  { title: "Breadcrumb", href: "/docs/components/breadcrumb" },
  { title: "Button", href: "/docs/components/button" },
  { title: "Calendar", href: "/docs/components/calendar" },
  { title: "Checkbox", href: "/docs/components/checkbox" },
  { title: "Chip", href: "/docs/components/chip" },
  { title: "Dialog", href: "/docs/components/dialog" },
  { title: "Drawer", href: "/docs/components/drawer" },
  { title: "Input", href: "/docs/components/input" },
  { title: "Json", href: "/docs/components/json" },
  { title: "Popover", href: "/docs/components/popover" },
  { title: "Radio", href: "/docs/components/radio" },
  { title: "RadioGroup", href: "/docs/components/radio-group" },
  { title: "Select", href: "/docs/components/select" },
  { title: "Spinner", href: "/docs/components/spinner" },
  { title: "Switch", href: "/docs/components/switch" },
  { title: "Tabs", href: "/docs/components/tabs" },
  { title: "Textarea", href: "/docs/components/textarea" },
];

export default sidebarConfig;
